//
//  Tag.swift
//  Jott
//
//  Created by Chris Shireman on 5/14/25.
//

import Foundation
import SwiftData

@Model
final class Tag {
    // Core properties
    var id: UUID
    var name: String
    var colorHex: String?  // Optional hex color code for visual differentiation
    
    // Metadata
    var createdAt: Date
    var usageCount: Int  // Track popularity for smart suggestions
    
    // ML-related properties
    var isAutoGenerated: Bool  // Flag for system-generated vs. user-created tags
    var confidenceScore: Double?  // For auto-generated tags, how confident is the ML model
    
    // Relationships
    @Relationship(deleteRule: .nullify)
    var notes: [Note] = []
    
    // Optional parent-child relationship for hierarchical tags
    @Relationship(deleteRule: .nullify)
    var parentTag: Tag?
    
    @Relationship(.unique, deleteRule: .nullify)
    var childTags: [Tag] = []
    
    init(
        id: UUID = UUID(),
        name: String,
        colorHex: String? = nil,
        createdAt: Date = Date(),
        usageCount: Int = 0,
        isAutoGenerated: Bool = false,
        confidenceScore: Double? = nil
    ) {
        self.id = id
        self.name = name
        self.colorHex = colorHex
        self.createdAt = createdAt
        self.usageCount = usageCount
        self.isAutoGenerated = isAutoGenerated
        self.confidenceScore = confidenceScore
    }
}
